### ISSUE TITLE
Using Ruby instead of R for scraping?

### ISSUE THREAD

**Issue by rpodcast** [toddwschneider/flim-springfield#1]
Thank you for creating such a great analysis of one of my favorite shows of all time!  This is more of a general question but were there specific reasons for using Ruby for the web scraping and database creation as opposed to R?  I plan on mentioning this analysis in my next episode of the podcast.

**Comment by toddwschneider** [comment]
@thercast I used Ruby/Rails because I like the ecosystem for making web requests, parsing HTML, and setting up database relationships. I'm sure everything could be done entirely within R, I just prefer Ruby for that kind of work
