### ISSUE TITLE
Error with bundle

### ISSUE THREAD

**Issue by pachadotdev** [toddwschneider/flim-springfield#2]
Hi

I obtain this when trying to run `bundle exec rake jobs:work`

`Job Character.set_genders (id=2) FAILED (5 prior attempts) with NoMethodError: undefined method 'gender=' for nil:NilClass`

**Comment by toddwschneider** [comment]
@pachamaltese sounds like the `set_genders` job is running before there are any records in the `characters` table

Can you confirm that there are records in the `episodes` table before you run `bundle exec rake jobs:work`?

Also, you can try modifying the `set_genders` method to this, then rerun and see what happens:

``` ruby
  def self.set_genders
    require 'csv'

    CSV.foreach("#{Rails.root}/analysis/data/character_genders.csv", headers: true) do |row|
      next unless c = find_by(normalized_name: row["normalized_name"])
      c.gender = row["gender"]
      c.save!
    end
  end
```

**Comment by pachadotdev** [comment]
Right. I'll get to you ASAP. Cheking now.

**Comment by toddwschneider** [comment]
@pachamaltese any update here?

**Comment by pachadotdev** [comment]
oh, sorry 
I did some trials (my students were interested on this). We had no sucess but at least we could recreate some plots.

**Comment by pachadotdev** [comment]
the same error had place on different computers running OS X, Windows and Ubuntu ...

**Comment by santi-d** [comment]
after to run scripts, no element is added to database :(

[Worker(host:hacuchis.pe.ibm.com pid:5473)] Starting job worker
[Worker(host:hacuchis.pe.ibm.com pid:5473)] Job Character.set_genders (id=2) RUNNING
[Worker(host:hacuchis.pe.ibm.com pid:5473)] Job Character.set_genders (id=2) COMPLETED after 0.1224
[Worker(host:hacuchis.pe.ibm.com pid:5473)] 1 jobs processed at 4.5335 j/s, 0 failed

**Comment by toddwschneider** [comment]
@focker321 @pachamaltese I wonder if the problem has to do with foreign languages. Any way you can simulate being in the US?

**Comment by pachadotdev** [comment]
Let me download Astrill and I'll tell you

**Comment by santi-d** [comment]
Hi, effectively, access to http://www.simpsonsworld.com/heartbeat is not allowed to my region is for this reason that the script does not generate all estructure.

Please can you share to us, the databases that you have? VPN does not work as I want... Thanks

**Comment by philchristensen** [comment]
That would be a quick way to get this project served a cease-and-desist from FOX.

**Comment by philchristensen** [comment]
I don't have cable, so I had to run this at work where we have Time Warner.

**Comment by toddwschneider** [comment]
@focker321 I do not have the data publicly available, but someone else has made it available here: https://www.kaggle.com/wcukierski/the-simpsons-by-the-data

I'm going to close this issue and note in the README that it's only known to work in the US
